--- #YAML:1.0
name: Mail-Thread-Arc
version: 0.10
license: perl
distribution_type: module
requires:
  Class::Accessor::Chained: 0
  Date::Parse: 0
  Mail::Thread: 2.4
  SVG: 0
  Test::More: 0
recommends: {}
build_requires: {}
conflicts: {}
provides:
  Mail::Thread::Arc:
    file: lib/Mail/Thread/Arc.pm
    version: 0.10
generated_by: Module::Build version 0.21
